### ISSUE TITLE
[Bug]: Error while opening the app for the first time. 

### ISSUE THREAD

**Issue by edfloreshz** [remindersdevs/Reminders#34]
### Package

Flathub

### Distribution

Fedora 38

### Describe the bug

When opening the app the following message is shown:

`Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gtk.Actions” on object at path /io/github/dgsasha/Remembrance`

Edit:

After trying to open the app again I was prompted with this:

```
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 86, in do_command_line
    self.do_activate()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 140, in do_activate
    self.connect_to_service()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 267, in connect_to_service
    self.service = Gio.DBusProxy.new_for_bus_sync(
gi.repository.GLib.GError: g-io-error-quark: Error calling StartServiceByName for io.github.dgsasha.Remembrance.Service2: Timeout was reached (24)
```

### To Reproduce

1. Run `flatpak run io.github.dgsasha.Remembrance`

### Logs

```shell
May 02 16:33:40 fedora flatpak[3408]: 2023-05-02 16:33:40,596 - remembrance-service - ERROR - ms_to_do:logout_all - g-io-error-quark: user interaction failed (0)
May 02 16:33:40 fedora flatpak[3408]: 2023-05-02 16:33:40,596 - remembrance-service - ERROR - application:__init__ - g-io-error-quark: user interaction failed (0)
```

**Comment by dgsasha** [comment]
Can you try logging out and logging back in once and then opening the app again? That's all I can really think of.

**Comment by edfloreshz** [comment]
I am using KDE Plasma 5.27.4, I did as you said but still getting the same error.

**Comment by edfloreshz** [comment]
After restarting I got this:
![Screenshot_20230502_172454](https://user-images.githubusercontent.com/22224438/235812371-66cb9bfb-9524-48a3-888e-3fd350131160.png)

**Comment by tripathiakshit** [comment]
Hello, I'm using GNOME on Arch, and the program refuses to start for me for the first time. Here is the trace:

```python
2023-05-03 13:59:04,339 - remembrance - INFO - application:connect_to_service - Connected to service
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 86, in do_command_line
    self.do_activate()
  File "/app/lib/python3.10/site-packages/remembrance/browser/application.py", line 144, in do_activate
    self.win = MainWindow(self.page, self)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 147, in __init__
    self.unpack_reminders(reminders)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 601, in unpack_reminders
    self.display_reminder(**reminder)
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 640, in display_reminder
    reminder = Reminder(
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 76, in __init__
    self.set_labels()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 268, in set_labels
    self.set_repeat_label()
  File "/app/lib/python3.10/site-packages/remembrance/browser/reminder.py", line 254, in set_repeat_label
    self.win.get_repeat_label(
  File "/app/lib/python3.10/site-packages/remembrance/browser/main_window.py", line 277, in get_repeat_label
    type_name = repeat_frequency + ' ' + _('hours')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by dgsasha** [comment]
Fix for this is coming in next release, closing.
